/**
 * @param {Record<string, unknown>} programme
 * @param {{ university?: Record<string, unknown> | null }} [options]
 */
export function buildProgrammePdfText(programme, { university = null } = {}) {
  const lines = [
    "THUTO — Programme Summary",
    "========================",
    "",
    `Programme: ${programme.name || "—"}`,
    `Institution: ${programme.university || "—"}`,
    programme.field ? `Field: ${programme.field}` : null,
    programme.duration ? `Duration: ${programme.duration}` : null,
    programme.studyMode ? `Study mode: ${programme.studyMode}` : null,
    Number.isFinite(programme.minPoints) ? `Minimum points: ${programme.minPoints}` : null,
    "",
    "Entry requirements",
    "------------------",
  ];

  const reqs = programme.subjectRequirements || {};
  const reqKeys = Object.keys(reqs);
  if (reqKeys.length) {
    for (const key of reqKeys) {
      lines.push(`• ${key}: at least ${reqs[key]}`);
    }
  } else {
    lines.push("Confirm subject requirements with the institution.");
  }

  const careers = programme.careers || programme.careerOpportunities || [];
  if (careers.length) {
    lines.push("", "Career prospects", "----------------", ...careers.map((c) => `• ${c}`));
  }

  if (programme.description) {
    lines.push("", "About", "-----", String(programme.description));
  }

  if (university?.applicationClose) {
    lines.push("", `Application deadline (indicative): ${university.applicationClose}`);
  }

  lines.push(
    "",
    "—",
    "Generated by Thuto (Botswana Tertiary Companion).",
    "This summary is for planning only. Confirm all details with the institution before applying.",
  );

  return lines.filter((line) => line != null).join("\n");
}

/**
 * @param {Record<string, unknown>} programme
 * @param {{ university?: Record<string, unknown> | null }} [options]
 */
export function downloadProgrammeSummary(programme, options = {}) {
  const text = buildProgrammePdfText(programme, options);
  const safeName = String(programme.name || programme.id || "programme")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `thuto-${safeName || "programme"}.txt`;
  anchor.click();
  URL.revokeObjectURL(url);
}

/**
 * @param {Record<string, unknown>} programme
 * @param {{ university?: Record<string, unknown> | null }} [options]
 */
export async function shareProgrammeSummary(programme, options = {}) {
  const text = buildProgrammePdfText(programme, options);
  const title = `${programme.name || "Programme"} — Thuto summary`;
  if (typeof navigator !== "undefined" && navigator.share) {
    await navigator.share({ title, text });
    return true;
  }
  downloadProgrammeSummary(programme, options);
  return false;
}
