/**
 * @param {{ programme: import('../lib/programmesData.js').Programme, university?: import('../lib/universitiesData.js').University | null }} props
 */
export default function PdfExportButton({ programme, university = null }) {
  function handleExport() {
    const lines = [
      `Thuto Programme Summary`,
      ``,
      `Programme: ${programme.name}`,
      `Institution: ${programme.university}`,
      programme.field ? `Field: ${programme.field}` : null,
      programme.duration ? `Duration: ${programme.duration}` : null,
      programme.minPoints != null ? `Minimum points: ${programme.minPoints} (best six)` : null,
      programme.fees?.domestic != null
        ? `Fees: ${programme.fees.currency || "BWP"} ${programme.fees.domestic}`
        : null,
      programme.applicationDeadline ? `Application deadline: ${programme.applicationDeadline}` : null,
      ``,
      programme.description ? `About:\n${programme.description}` : null,
      ``,
      `Generated by Thuto — confirm all details officially before applying.`,
      university?.website ? `Institution: ${university.website}` : null,
    ].filter(Boolean);

    const blob = new Blob([lines.join("\n")], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = `${programme.id}-summary.txt`;
    anchor.click();
    URL.revokeObjectURL(url);
  }

  async function handleShare() {
    const text = `${programme.name} at ${programme.university} — summary from Thuto`;
    const url = `${window.location.origin}${import.meta.env.BASE_URL || ""}/programmes/${programme.id}`;
    if (navigator.share) {
      try {
        await navigator.share({ title: programme.name, text, url });
        return;
      } catch {
        /* fall through */
      }
    }
    const wa = `https://wa.me/?text=${encodeURIComponent(`${text}\n${url}`)}`;
    window.open(wa, "_blank", "noopener,noreferrer");
  }

  return (
    <div className="flex flex-wrap gap-2">
      <button
        type="button"
        onClick={handleExport}
        className="rounded-xl border border-brand-200 bg-white px-4 py-2 text-sm font-semibold text-brand-800 hover:bg-brand-50"
      >
        Download summary
      </button>
      <button
        type="button"
        onClick={handleShare}
        className="rounded-xl bg-brand-700 px-4 py-2 text-sm font-semibold text-white hover:bg-brand-800"
      >
        Share via WhatsApp
      </button>
    </div>
  );
}
