import { ascendingNumeric, defineProfile, descendingNumeric } from "./builders.js";

export const EASTERN_PROFILES = {
  kcse: defineProfile({
    id: "kcse",
    label: "KCSE — Kenya Certificate of Secondary Education",
    abbreviation: "KCSE",
    aliases: ["kcse", "kenya", "knec", "form four"],
    countries: ["ke"],
    region: "eastern",
    verified: true,
    sourceNote: "KNEC 12-point scale (A=12 down to E=1). University placement also uses cluster points.",
    grades: [
      { value: "A", label: "A — 12 points", points: 12, band: "A*" },
      { value: "A-", label: "A− — 11 points", points: 11, band: "A" },
      { value: "B+", label: "B+ — 10 points", points: 10, band: "A" },
      { value: "B", label: "B — 9 points", points: 9, band: "B" },
      { value: "B-", label: "B− — 8 points", points: 8, band: "B" },
      { value: "C+", label: "C+ — 7 points", points: 7, band: "C" },
      { value: "C", label: "C — 6 points", points: 6, band: "C" },
      { value: "C-", label: "C− — 5 points", points: 5, band: "D" },
      { value: "D+", label: "D+ — 4 points", points: 4, band: "D" },
      { value: "D", label: "D — 3 points", points: 3, band: "E" },
      { value: "D-", label: "D− — 2 points", points: 2, band: "F" },
      { value: "E", label: "E — 1 point", points: 1, band: "U" },
    ],
    subjectsCounted: 7,
    aggregate: "meanGrade",
    aggregateLabel: "Best-seven points total",
    helpText:
      "KCSE 12-point scale across your best seven subjects. Kenyan university placement also uses subject cluster points — confirm with KUCCPS.",
    examBoards: ["igcse", "bgcse"],
  }),

  necta_csee: defineProfile({
    id: "necta_csee",
    label: "CSEE — Tanzania Certificate of Secondary Education",
    abbreviation: "CSEE",
    aliases: ["csee", "necta", "tanzania", "form four tanzania"],
    countries: ["tz"],
    region: "eastern",
    verified: false,
    sourceNote:
      "NECTA CSEE A-F with division bands (Division I is the strongest). The per-grade point values used here are not confirmed against NECTA.",
    grades: [
      { value: "A", label: "A — 1 point", points: 1, band: "A*" },
      { value: "B", label: "B — 2 points", points: 2, band: "A" },
      { value: "C", label: "C — 3 points", points: 3, band: "C" },
      { value: "D", label: "D — 4 points", points: 4, band: "E" },
      { value: "F", label: "F — 5 points", points: 5, band: "U" },
    ],
    direction: "lower_better",
    subjectsCounted: 7,
    aggregate: "aggregatePoints",
    aggregateLabel: "Best-seven points (lower is better)",
    helpText: "NECTA CSEE points where a lower total is stronger. Division I is roughly 7–17 points.",
    examBoards: ["igcse", "bgcse"],
  }),

  necta_acsee: defineProfile({
    id: "necta_acsee",
    label: "ACSEE — Tanzania Advanced Certificate of Secondary Education",
    abbreviation: "ACSEE",
    aliases: ["acsee", "tanzania a level", "form six"],
    countries: ["tz"],
    region: "eastern",
    level: "advanced",
    verified: true,
    sourceNote: "NECTA ACSEE principal subjects: A=5, B=4, C=3, D=2, E=1, S=0.5, F=0.",
    grades: [
      { value: "A", points: 5, band: "A*" },
      { value: "B", points: 4, band: "A" },
      { value: "C", points: 3, band: "B" },
      { value: "D", points: 2, band: "C" },
      { value: "E", points: 1, band: "D" },
      { value: "S", label: "S — subsidiary", points: 0.5, band: "E" },
      { value: "F", points: 0, band: "U" },
    ],
    subjectsCounted: 3,
    aggregate: "advancedPoints",
    aggregateLabel: "Three principal subjects",
    helpText: "ACSEE principal subject points (max 15 across three subjects).",
    examBoards: ["igcse", "bgcse"],
  }),

  uneb_uce: defineProfile({
    id: "uneb_uce",
    label: "UCE — Uganda Certificate of Education (O Level)",
    abbreviation: "UCE",
    aliases: ["uce", "uneb", "uganda o level", "uganda"],
    countries: ["ug"],
    region: "eastern",
    verified: false,
    sourceNote:
      "UNEB UCE distinction/credit/pass grades where a lower number is stronger. The best-eight aggregate rule is not confirmed against UNEB.",
    grades: descendingNumeric({
      from: 1,
      to: 9,
      values: { 1: "D1", 2: "D2", 3: "C3", 4: "C4", 5: "C5", 6: "C6", 7: "P7", 8: "P8", 9: "F9" },
      bands: { 1: "A*", 2: "A", 3: "B", 4: "B", 5: "C", 6: "C", 7: "D", 8: "E", 9: "U" },
      labels: {
        1: "D1 — Distinction",
        2: "D2 — Distinction",
        3: "C3 — Credit",
        4: "C4 — Credit",
        5: "C5 — Credit",
        6: "C6 — Credit",
        7: "P7 — Pass",
        8: "P8 — Pass",
        9: "F9 — Fail",
      },
    }),
    direction: "lower_better",
    subjectsCounted: 8,
    aggregate: "aggregatePoints",
    aggregateLabel: "Best-eight aggregate (lower is better)",
    helpText: "UNEB UCE grades where D1 is strongest. A lower aggregate is a stronger result.",
    examBoards: ["igcse", "bgcse"],
  }),

  uneb_uace: defineProfile({
    id: "uneb_uace",
    label: "UACE — Uganda Advanced Certificate of Education (A Level)",
    abbreviation: "UACE",
    aliases: ["uace", "uganda a level", "senior six"],
    countries: ["ug"],
    region: "eastern",
    level: "advanced",
    verified: true,
    sourceNote:
      "Weighting used by Ugandan universities for principal subjects: A=6, B=5, C=4, D=3, E=2, O=1, F=0. This is an institutional convention, not a UNEB scale.",
    grades: ascendingNumeric({
      from: 0,
      to: 6,
      bands: { 6: "A*", 5: "A", 4: "B", 3: "C", 2: "D", 1: "F", 0: "U" },
      labels: {
        6: "A — 6 points",
        5: "B — 5 points",
        4: "C — 4 points",
        3: "D — 3 points",
        2: "E — 2 points",
        1: "O — subsidiary pass",
        0: "F — fail",
      },
    }),
    subjectsCounted: 3,
    aggregate: "advancedPoints",
    aggregateLabel: "Three principal subjects",
    helpText: "UACE principal subject points (max 18 across three subjects), plus subsidiaries where allowed.",
    examBoards: ["igcse", "bgcse"],
  }),

  rw_alevel: defineProfile({
    id: "rw_alevel",
    label: "Rwanda A-Level (Senior 6)",
    abbreviation: "A2",
    aliases: ["rwanda", "nesa", "senior six", "a2", "rwanda a level"],
    countries: ["rw"],
    region: "eastern",
    level: "advanced",
    verified: true,
    sourceNote: "NESA competence-based grading, principal subjects A=6 down to U=0.",
    grades: ascendingNumeric({
      from: 0,
      to: 6,
      bands: { 6: "A*", 5: "A", 4: "B", 3: "C", 2: "D", 1: "F", 0: "U" },
      labels: {
        6: "A — 6 points",
        5: "B — 5 points",
        4: "C — 4 points",
        3: "D — 3 points",
        2: "E — 2 points",
        1: "S — subsidiary",
        0: "U — ungraded",
      },
    }),
    subjectsCounted: 3,
    aggregate: "advancedPoints",
    aggregateLabel: "Three principal subjects",
    helpText: "Rwanda A-Level principal subject points (max 18 across three subjects).",
    examBoards: ["igcse", "bgcse"],
  }),

  euee: defineProfile({
    id: "euee",
    label: "EUEE — Ethiopian University Entrance Examination",
    abbreviation: "EUEE",
    aliases: ["euee", "ethiopia", "neaea", "grade 12 ethiopia"],
    countries: ["et"],
    region: "eastern",
    verified: false,
    sourceNote:
      "EUEE is scored out of 100 per subject across roughly seven subjects. Entry cut-offs are set nationally each year and are not encoded here.",
    grades: [
      { value: "90", label: "90–100", points: 90, band: "A*" },
      { value: "80", label: "80–89", points: 80, band: "A" },
      { value: "70", label: "70–79", points: 70, band: "B" },
      { value: "60", label: "60–69", points: 60, band: "C" },
      { value: "50", label: "50–59", points: 50, band: "D" },
      { value: "40", label: "40–49", points: 40, band: "E" },
      { value: "0", label: "Below 40", points: 0, band: "U" },
    ],
    subjectsCounted: 7,
    minPerSubject: 0,
    maxPerSubject: 100,
    aggregate: "totalScore",
    aggregateLabel: "Total score",
    helpText: "Enter your per-subject EUEE scores. National cut-off points change each year — confirm with NEAEA.",
    examBoards: ["igcse", "bgcse"],
  }),
};
