import { ascendingNumeric, bandedScale, defineProfile, descendingNumeric, letterLadder } from "./builders.js";

/** Cambridge A*-G points shared by BGCSE, IGCSE, NSSC, LGCSE. */
const CAMBRIDGE_8 = { "A*": 8, A: 8, B: 7, C: 6, D: 5, E: 4, F: 3, G: 2, U: 0 };
/** Same ladder without A*, used by boards that never issued one. */
const CAMBRIDGE_8_NO_STAR = { A: 8, B: 7, C: 6, D: 5, E: 4, F: 3, G: 2, U: 0 };
/** Advanced-level A-E ladder. */
const ADVANCED_5 = { A: 5, B: 4, C: 3, D: 2, E: 1, U: 0 };

export const SOUTHERN_PROFILES = {
  bgcse: defineProfile({
    id: "bgcse",
    label: "BGCSE — Botswana General Certificate of Secondary Education",
    abbreviation: "BGCSE",
    aliases: ["bgcse", "botswana", "form 5", "botswana general certificate"],
    countries: ["bw"],
    region: "southern",
    verified: true,
    sourceNote: "UB and BIUST admissions guides. A* counts the same as A.",
    grades: letterLadder(CAMBRIDGE_8),
    subjectsCounted: 6,
    aggregate: "bestSix",
    aggregateLabel: "Best-six total",
    helpText: "Official Botswana BGCSE points. Best six subjects count (max 48).",
    examBoards: ["bgcse"],
    allowsScienceDouble: true,
  }),

  igcse: defineProfile({
    id: "igcse",
    label: "IGCSE — International General Certificate of Secondary Education",
    abbreviation: "IGCSE",
    aliases: ["igcse", "cambridge", "cie", "international gcse"],
    countries: ["bw", "na", "zw", "zm", "za", "ke", "gh", "ng", "mu"],
    region: "southern",
    verified: true,
    sourceNote: "Cambridge IGCSE A*-G, mapped onto the BGCSE best-six style total for matching.",
    grades: letterLadder(CAMBRIDGE_8),
    subjectsCounted: 6,
    aggregate: "bestSix",
    aggregateLabel: "Best-six total",
    helpText: "IGCSE letter grades mapped to a best-six style total for guidance matching.",
    examBoards: ["igcse"],
    allowsScienceDouble: true,
  }),

  o_level: defineProfile({
    id: "o_level",
    label: "Cambridge O Level",
    abbreviation: "O Level",
    aliases: ["o level", "olevel", "ordinary level", "gce o"],
    countries: ["bw", "zw", "zm", "mw", "mu"],
    region: "southern",
    verified: true,
    sourceNote: "Cambridge O Level A-G ladder.",
    grades: letterLadder(CAMBRIDGE_8_NO_STAR),
    subjectsCounted: 6,
    aggregate: "bestSix",
    aggregateLabel: "Best-six total",
    helpText: "O-Level letter grades with a best-six style total for guidance matching.",
    examBoards: ["igcse"],
  }),

  as_level: defineProfile({
    id: "as_level",
    label: "Cambridge AS Level",
    abbreviation: "AS",
    aliases: ["as level", "as", "advanced subsidiary"],
    countries: ["bw", "zw", "zm", "za", "na"],
    region: "southern",
    level: "advanced",
    verified: true,
    sourceNote: "AS Level A-E. Students normally sit three subjects, so three are counted — not six.",
    grades: letterLadder(ADVANCED_5),
    subjectsCounted: 3,
    aggregate: "advancedPoints",
    aggregateLabel: "AS points total",
    helpText: "AS Level A–E scale for guidance. Confirm official university equivalencies.",
    examBoards: ["igcse"],
  }),

  a_level: defineProfile({
    id: "a_level",
    label: "Cambridge / Pearson A Level",
    abbreviation: "A Level",
    aliases: ["a level", "alevel", "advanced level", "gce a"],
    countries: ["bw", "zw", "zm", "za", "na", "mu", "ng", "gh"],
    region: "southern",
    level: "advanced",
    verified: true,
    sourceNote: "A Level A*-E, three principal subjects.",
    grades: letterLadder({ "A*": 6, A: 5, B: 4, C: 3, D: 2, E: 1, U: 0 }),
    subjectsCounted: 3,
    aggregate: "advancedPoints",
    aggregateLabel: "A Level points total",
    helpText: "Three principal A Level subjects (max 18). Universities set their own subject rules.",
    examBoards: ["igcse"],
  }),

  nssc: defineProfile({
    id: "nssc",
    label: "NSSC — Namibia Senior Secondary Certificate",
    abbreviation: "NSSC",
    aliases: ["nssc", "namibia", "nssco", "nsscas"],
    countries: ["na"],
    region: "southern",
    verified: false,
    sourceNote:
      "Namibia replaced NSSCH with NSSCAS; the split between the Ordinary and Advanced Subsidiary scales is not confirmed here.",
    grades: letterLadder(CAMBRIDGE_8),
    subjectsCounted: 6,
    aggregate: "bestSix",
    aggregateLabel: "Best-six total",
    helpText: "Namibia NSSC letter grades (guidance scale). Confirm official institutional conversions.",
    examBoards: ["igcse"],
  }),

  lgcse: defineProfile({
    id: "lgcse",
    label: "LGCSE — Lesotho General Certificate of Secondary Education",
    abbreviation: "LGCSE",
    aliases: ["lgcse", "lesotho", "ecol"],
    countries: ["ls"],
    region: "southern",
    verified: false,
    sourceNote: "Cambridge-derived A*-G ladder. Not confirmed against an ECoL source.",
    grades: letterLadder(CAMBRIDGE_8),
    subjectsCounted: 6,
    aggregate: "bestSix",
    aggregateLabel: "Best-six total",
    helpText: "Lesotho LGCSE letter grades (guidance scale).",
    examBoards: ["igcse"],
  }),

  egcse: defineProfile({
    id: "egcse",
    label: "EGCSE — Eswatini General Certificate of Secondary Education",
    abbreviation: "EGCSE",
    aliases: ["egcse", "eswatini", "swaziland", "examinations council of eswatini"],
    countries: ["sz"],
    region: "southern",
    verified: false,
    sourceNote: "Cambridge-derived ladder. Not confirmed against an ECESWA source.",
    grades: letterLadder(CAMBRIDGE_8_NO_STAR),
    subjectsCounted: 6,
    aggregate: "bestSix",
    aggregateLabel: "Best-six total",
    helpText: "Eswatini EGCSE letter grades (guidance scale).",
    examBoards: ["igcse"],
  }),

  zimsec_o: defineProfile({
    id: "zimsec_o",
    label: "ZIMSEC O Level",
    abbreviation: "ZIMSEC O",
    aliases: ["zimsec", "zimsec o", "zimbabwe o level", "zimbabwe"],
    countries: ["zw"],
    region: "southern",
    verified: false,
    sourceNote: "ZIMSEC O Level A-U guidance scale. Point convention not confirmed against ZIMSEC.",
    grades: letterLadder(CAMBRIDGE_8_NO_STAR),
    subjectsCounted: 6,
    aggregate: "bestSix",
    aggregateLabel: "Best-six total",
    helpText: "ZIMSEC O-Level guidance scale. Many Zimbabwe programmes also expect A-Level passes.",
    examBoards: ["igcse"],
  }),

  zimsec_a: defineProfile({
    id: "zimsec_a",
    label: "ZIMSEC A Level",
    abbreviation: "ZIMSEC A",
    aliases: ["zimsec a", "zimbabwe a level"],
    countries: ["zw"],
    region: "southern",
    level: "advanced",
    verified: false,
    sourceNote: "ZIMSEC A Level A-E guidance scale, three principal subjects. Point convention unconfirmed.",
    grades: letterLadder(ADVANCED_5),
    subjectsCounted: 3,
    aggregate: "advancedPoints",
    aggregateLabel: "A-Level points total",
    helpText: "ZIMSEC A-Level A–E guidance scale. Universities often require specific subject passes.",
    examBoards: ["igcse"],
  }),

  ecz: defineProfile({
    id: "ecz",
    label: "ECZ School Certificate — Zambia",
    abbreviation: "ECZ",
    aliases: ["ecz", "zambia", "school certificate", "grade 12 zambia"],
    countries: ["zm"],
    region: "southern",
    verified: true,
    sourceNote: "ECZ grades 1-9, 1 strongest; 1-6 are credit passes. Best-six aggregate runs 6 (best) to 54.",
    grades: descendingNumeric({
      from: 1,
      to: 9,
      bands: { 1: "A*", 2: "A", 3: "B", 4: "B", 5: "C", 6: "C", 7: "D", 8: "E", 9: "U" },
      labels: {
        1: "1 — Distinction",
        2: "2 — Distinction",
        3: "3 — Merit",
        4: "4 — Merit",
        5: "5 — Credit",
        6: "6 — Credit",
        7: "7 — Satisfactory",
        8: "8 — Satisfactory",
        9: "9 — Unsatisfactory",
      },
    }),
    direction: "lower_better",
    subjectsCounted: 6,
    aggregate: "aggregatePoints",
    aggregateLabel: "Best-six aggregate (lower is better)",
    helpText: "ECZ grades 1–9 where 1 is strongest. Aggregate 6 is the best possible — confirm official cut-offs.",
    examBoards: ["igcse", "bgcse"],
  }),

  msce: defineProfile({
    id: "msce",
    label: "MSCE — Malawi School Certificate of Education",
    abbreviation: "MSCE",
    aliases: ["msce", "malawi", "maneb"],
    countries: ["mw"],
    region: "southern",
    verified: true,
    sourceNote: "MANEB grades 1-9 where 1 is strongest; NCHE minimum entry uses a best-six aggregate.",
    grades: descendingNumeric({
      from: 1,
      to: 9,
      bands: { 1: "A*", 2: "A", 3: "B", 4: "B", 5: "C", 6: "C", 7: "D", 8: "E", 9: "U" },
    }),
    direction: "lower_better",
    subjectsCounted: 6,
    aggregate: "aggregatePoints",
    aggregateLabel: "Best-six aggregate (lower is better)",
    helpText: "MSCE grades 1–9 where 1 is strongest. Aggregate 6 is the best possible.",
    examBoards: ["igcse", "bgcse"],
  }),

  nsc_matric: defineProfile({
    id: "nsc_matric",
    label: "NSC — National Senior Certificate (Matric)",
    abbreviation: "NSC",
    aliases: ["nsc", "matric", "aps", "grade 12", "national senior certificate", "umalusi", "south africa"],
    countries: ["za"],
    region: "southern",
    verified: true,
    sourceNote:
      "Achievement levels 1-7 mapped 1:1 to APS. Most universities exclude Life Orientation from the six counted subjects.",
    grades: ascendingNumeric({
      from: 1,
      to: 7,
      bands: { 7: "A*", 6: "A", 5: "B", 4: "C", 3: "D", 2: "E", 1: "U" },
      labels: {
        7: "7 — Outstanding (80–100%)",
        6: "6 — Meritorious (70–79%)",
        5: "5 — Substantial (60–69%)",
        4: "4 — Adequate (50–59%)",
        3: "3 — Moderate (40–49%)",
        2: "2 — Elementary (30–39%)",
        1: "1 — Not achieved (0–29%)",
      },
    }),
    subjectsCounted: 6,
    aggregate: "aps",
    aggregateLabel: "APS total",
    helpText:
      "APS from your best six subjects, excluding Life Orientation (max 42). Each university sets its own APS rules.",
    examBoards: ["igcse", "bgcse"],
  }),

  lusophone_20: defineProfile({
    id: "lusophone_20",
    label: "12ª Classe (Lusophone, /20)",
    abbreviation: "12ª",
    aliases: ["12a classe", "12 classe", "lusophone", "angola", "mocambique", "mozambique", "cabo verde", "media"],
    countries: ["ao", "mz", "cv", "gw", "st"],
    region: "southern",
    verified: true,
    sourceNote: "Lusophone 0–20 classification scale. Institutional admission thresholds are not confirmed.",
    grades: bandedScale([
      { value: 18, label: "18–20 — Excelente", band: "A*" },
      { value: 16, label: "16–17 — Muito bom", band: "A" },
      { value: 14, label: "14–15 — Bom", band: "B" },
      { value: 12, label: "12–13 — Suficiente alto", band: "C" },
      { value: 10, label: "10–11 — Suficiente (aprovado)", band: "D" },
      { value: 8, label: "8–9 — Insuficiente", band: "F" },
      { value: 0, label: "Below 8 — Reprovado", band: "U" },
    ]),
    subjectsCounted: 6,
    minPerSubject: 0,
    maxPerSubject: 20,
    aggregate: "average20",
    aggregateLabel: "Best-six total /20 per subject",
    helpText:
      "Enter the classificação for each subject out of 20, or the closest band. Institutions assess these case by case.",
    examBoards: ["igcse", "bgcse"],
  }),
};
